const fs=require('fs'),path=require('path'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const d=require('../src/app/filter/filterData.ts'),e=require('../src/app/filter/filterExport.ts');
const groups=['EXCEPTIONAL_GROUPS','WAYSTONE_GROUPS','UNIQUE_ARMOUR_GROUPS','UNIQUE_GROUPS','OTHER_UNIQUE_GROUPS','TABLET_GROUPS','JEWEL_GROUPS','FLASK_GROUPS','CHARM_GROUPS','CURRENCY_GROUPS','ESSENCE_GROUPS','DELIRIUM_GROUPS','BREACH_GROUPS','ABYSS_GROUPS','ATZIRI_GROUPS','FRAGMENT_GROUPS','RUNE_GROUPS','RITUAL_GROUPS','SOUL_CORE_GROUPS','IDOL_GROUPS','UNCUT_GEM_GROUPS','EXPEDITION_GROUPS','LINEAGE_GEM_GROUPS','MISC_GROUPS'];
const items=groups.flatMap(x=>d[x].flatMap(g=>g.items));const normals=d.NORMAL_GEAR_GROUPS.flatMap(g=>g.items.map(i=>({...i,classNames:g.classes})));
const desc={masitda:{choice:'masitda',filterPath:'FIXLGS_SOUNDS/masitda.mp3'}};
for(const id of d.NEVER_SINK_STRICTNESSES.map(x=>x.id)) {
 const baseline=require('../public/neversink/0.10.4/baseline/'+id+'.json');const inp={base:{id,version:'0.10.4',text:fs.readFileSync(path.join(__dirname,'../public/neversink/0.10.4/'+id+'.filter'),'utf8')},items,itemState:{},baselineEnabled:k=>baseline.items[k]?.enabled??false,baselineStatus:k=>baseline.items[k]?.status??'missing',soundState:{},soundDescriptors:desc,rareTiers:{},magicTiers:{},rareGear:{},magicGear:{},normalItems:normals,normalGear:{},normalBaselineEnabled:k=>baseline.normal[k]?.enabled??false,normalBaselineStatus:k=>baseline.normal[k]?.status??'missing',normalBaselineImportance:k=>baseline.normal[k]?.importance??'default',normalImportance:{},normalLevelRules:{}};
 for(const item of items) { inp.soundState={[item.id]:'masitda'};try {e.buildCustomizedFilter(inp)} catch(err){ if(String(err).includes('적용 불일치'))console.log(JSON.stringify({id,item:item.id,base:item.baseType,level:item.gemLevel,section:item.sourceSection,status:baseline.items[item.id]?.status,enabled:baseline.items[item.id]?.enabled,error:String(err).slice(0,190)}));else console.log('OTHER ERROR '+err)}}
}
